### PR TITLE
Work for release 4.5.0-rc1, Add eclipse-neon profile to plugin-profiles dependency

### PR DESCRIPTION
**Pull request by wpopielarski**

### CODE REVIEW

**Comment by wpopielarski** [comment]
retest this please

**Comment by wpopielarski** [comment]
Looks like jenkins build needs update too. The eclipse profile have to be set to 'eclipse-neon' (like in build.sh) because of change in eclipse API (`getAdapter` changed its signature).

**Comment by sschaef** [comment]
retest this please

**Comment by sschaef** [comment]
There is a merge error in the PR. One commit appears three times.

**Comment by wpopielarski** [comment]
retest this please

**Comment by wpopielarski** [comment]
ok, looks fixed, thanks @sschaef

**Comment by sschaef** [comment]
There are still merge errors here. I guess it is best if you open a new PR with the necessary changes.

**Comment by wpopielarski** [comment]
will be replaced

**Pull request closed without merging**
